#pragma once

namespace Firebox {

	enum class APIEnum
	{
		// Masks
		API_DEPTH_BUFFER_BIT,
		API_STENCIL_BUFFER_BIT,
		API_COLOR_BUFFER_BIT,

		// Booleans
		API_FALSE,
		API_TRUE,

		// Primitive types
		API_POINTS,
		API_LINES,
		API_LINE_LOOP,
		API_LINE_STRIP,
		API_TRIANGLES,
		API_TRIANGLE_STRIP,
		API_TRIANGLE_FAN,
		API_QUADS,

		// Depth/stencil comparison functions
		API_NEVER,
		API_LESS,
		API_EQUAL,
		API_LEQUAL,
		API_GREATER,
		API_NOTEQUAL,
		API_GEQUAL,
		API_ALWAYS,

		// Blend factors
		API_ZERO,
		API_ONE,
		API_SRC_COLOR,
		API_ONE_MINUS_SRC_COLOR,
		API_SRC_ALPHA,
		API_ONE_MINUS_SRC_ALPHA,
		API_DST_ALPHA,
		API_ONE_MINUS_DST_ALPHA,
		API_DST_COLOR,
		API_ONE_MINUS_DST_COLOR,
		API_SRC_ALPHA_SATURATE,

		API_FRAMEBUFFER
	};
}