#pragma once

#include "SDL3/SDL.h"

namespace Firebox {
	enum MouseCode
	{
		FBK_MOUSE_BUTTON_LEFT = SDL_BUTTON_LEFT,
		FBK_MOUSE_BUTTON_RIGHT = SDL_BUTTON_RIGHT,
		FBK_MOUSE_BUTTON_MIDDLE = SDL_BUTTON_MIDDLE,
		FBK_MOUSE_BUTTON_X1 = SDL_BUTTON_X1,
		FBK_MOUSE_BUTTON_X2 = SDL_BUTTON_X2
	};
}