#pragma once

#include "SDL3/SDL.h"

namespace Firebox {

	enum GamepadButtonCode
	{
		FBK_GAMEPAD_BUTTON_BOTTOM = SDL_GAMEPAD_BUTTON_SOUTH,
		FBK_GAMEPAD_BUTTON_TOP = SDL_GAMEPAD_BUTTON_NORTH,
		FBK_GAMEPAD_BUTTON_LEFT = SDL_GAMEPAD_BUTTON_WEST,
		FBK_GAMEPAD_BUTTON_RIGHT = SDL_GAMEPAD_BUTTON_EAST
	};
}